# Generated by Django 4.1.7 on 2024-12-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
