# Generated by Django 4.1.7 on 2024-12-20 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ideasubmission')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funded_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ideasubmission')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.investor')),
            ],
        ),
    ]
