# Generated by Django 4.1.7 on 2025-01-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorinterest',
            old_name='interested_at',
            new_name='datetime',
        ),
    ]
