# Generated by Django 4.1.7 on 2025-01-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_rename_interested_at_investorinterest_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorfunding',
            old_name='funded_at',
            new_name='datetime',
        ),
    ]
