# Generated by Django 4.1.7 on 2025-01-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_rename_funded_at_investorfunding_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinterest',
            name='amount_range',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
