# Generated by Django 4.1.7 on 2024-12-20 05:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('funded_at', models.DateTimeField(auto_now_add=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('idea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='student.ideasubmission')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='userauth.investor')),
            ],
        ),
    ]
