# Generated by Django 4.1.7 on 2024-12-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='admin_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
