# Generated by Django 4.1.7 on 2024-12-24 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('student', '0002_ideasubmission_admin_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupparticipant',
            name='group',
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='stud_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauth.student'),
            preserve_default=False,
        ),
    ]
