# Generated by Django 4.1.7 on 2024-12-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_groupparticipant_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasubmission',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
    ]
