# Generated by Django 4.1.7 on 2024-12-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_ideasubmission_admin_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='is_single_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='name_of_group',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='number_of_member',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='project_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
