# Generated by Django 4.1.7 on 2024-12-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_ideasubmission_is_single_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasubmission',
            name='name_of_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='number_of_member',
            field=models.IntegerField(null=True),
        ),
    ]
