# Generated by Django 4.1.7 on 2024-12-20 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=10)),
                ('role', models.CharField(default='Investor', max_length=50)),
                ('domain', models.CharField(max_length=150)),
                ('linked_url', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=150)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('max_otp_try', models.IntegerField(default=3)),
                ('otp_max_out', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('password_reset_otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=10)),
                ('role', models.CharField(default='Student', max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('max_otp_try', models.IntegerField(default=3)),
                ('otp_max_out', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('password_reset_otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('is_group_leader', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('field_of_study', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField()),
            ],
        ),
    ]
