# Generated by Django 4.1.7 on 2024-12-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
    ]
