# Generated by Django 4.1.7 on 2025-01-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_investor_admin_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_degree',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='linked_url',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='post_graduation_degree',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
