# Generated by Django 4.1.7 on 2025-01-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_student_graduation_degree_student_linked_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduation_degree',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='post_graduation_degree',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
