# Generated by Django 4.1.7 on 2025-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_student_graduation_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_members',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='group_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
