# Generated by Django 4.1.7 on 2025-01-12 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_student_group_members_student_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email1',
            field=models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='student',
            name='email2',
            field=models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='student',
            name='email3',
            field=models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='student',
            name='email4',
            field=models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
